extends Panel


# Declare member variables here. Examples:
# var a = 2
# var b = "text"


# Called when the node enters the scene tree for the first time.
func _ready():
	pass # Replace with function body.


# Called every frame. 'delta' is the elapsed time since the previous frame.
#func _process(delta):
#	pass

func _on_nametag_pressed():
	get_tree().paused = true
	show()

func _on_resume_button_pressed():
	get_tree().paused = false
	hide()

func _on_confirm_rename_button_pressed():
	var new_name = get_node("rename_input").text
	get_parent().get_parent().update_fish_name(new_name)
